version: '3.8'

services:

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=note

  frontend:
    build: ./frontend
    volumes:
      - './:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start


  web:
    build: ./note
    command: uvicorn app:app --host 0.0.0.0 --port 8080
    depends_on:
      - mongo
    ports:
      - "8080:8080"
